# --------------------------------------------
# SERVER CONFIG
# --------------------------------------------
server.port=9090

# --------------------------------------------
# DATABASE CONFIG (PostgreSQL)
# --------------------------------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/devpulse_db
spring.datasource.username=postgres
spring.datasource.password=Ddevi@111
spring.datasource.driver-class-name=org.postgresql.Driver

# --------------------------------------------
# JPA / HIBERNATE CONFIG
# --------------------------------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Format SQL output (optional but useful)
spring.jpa.properties.hibernate.format_sql=true

# --------------------------------------------
# THYMELEAF CONFIG
# --------------------------------------------
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# --------------------------------------------
# LOGGING (Optional - cleaner console output)
# --------------------------------------------
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE




server.servlet.session.tracking-modes=cookie
server.servlet.session.timeout=30m

